[colors.primary]
background = "#FFF7EB"
foreground = "#2D2424"

[colors.normal]
black = "#483939"
red = "#AE4750"
green = "#C6695D"
yellow = "#CD9165"
blue = "#97916F"
magenta = "#7B727E"
cyan = "#83546B"
white = "#E0CFC6"

[colors.bright]
black = "#9C8181"
red = "#C8767D"
green = "#DB9A91"
yellow = "#D4A391"
blue = "#AFA49B"
magenta = "#A69DA4"
cyan = "#A3728B"
white = "#FFF7EB"
